#Constants informations
/provider_hydrophone/hydrophone/snr_threshold : 10
/provider_hydrophone/hydrophone/signal_threshold: 35000
/provider_hydrophone/hydrophone/gain: 4

#/provider_hydrophone/connection/tty_port: "/dev/HYDRO"
